import Head from 'next/head'
import { useContext, useEffect, useMemo } from 'react'
import { async } from 'regenerator-runtime'
import { object } from 'webidl-conversions'
import Header from '../components/Header.js'
import NavBar from "../components/NavBar.js"
import Results from "../components/Results.js"
import requests from "../utils/requests.js"

export default function Home({ results }) {

  console.log([results])
  return (
    <div>
      <Head>
        <title>AresDB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* Header */}
      <Header/>

      {/* NavBar */}
      <NavBar/>

      {/* Results */}
      <Results results={results}/>
      
    </div>
  )
}

export async function getServerSideProps(context){
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
        requests[genre]?.url || requests.fetchTrending.url
    }`
    ).then((res) => res.json())
    
    return {
      props: {
        results: request.results,
      },
    }
}
