import Head from 'next/head'
import Header from '../components/Header.js'
import NavBar from "../components/NavBar.js"

export default function Home() {
  return (
    <div>
      <Head>
        <title>AresDB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* Header */}
      <Header/>

      {/* NavBar */}
      <NavBar/>
      
    </div>
  )
}
